FROM jenkinsci/jnlp-slave

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    curl
    
ENV VERSION "17.03.1-ce"
RUN curl -L -o /tmp/docker-$VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VERSION.tgz \
    && tar -xz -C /tmp -f /tmp/docker-$VERSION.tgz \
    && mv /tmp/docker/docker /usr/bin \
    && rm -rf /tmp/docker-$VERSION /tmp/docker

ADD ./cvte/apache-maven-3.6.0-bin.tar.gz /usr/local/
RUN ln -s /usr/local/apache-maven-3.6.0/bin/mvn /usr/bin/mvn
