name: Publish DockerHub
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Jenkins to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: seew0nic/jenkins
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          snapshot: true
          dockerfile: Dockerfile-cvte
